### ISSUE TITLE
Google Auth: Not a valid origin for the client

### ISSUE THREAD

**Issue by sshclub** [scitronboy/cloud-storage-dashboard#2]
hello.
Thank you so much for making such a good source code.

I'm trying to clone the code and install it. Google authentication doesn't work.

May I know the cause?

{error: 'idpiframe_initialization_failed', details: "Not a valid origin for the client: http://localhos…egister this origin for your project's client ID."}
details: "Not a valid origin for the client: http://localhost:3000 has not been registered for client ID config.googleClientId. Please go to https://console.developers.google.com/ and register this origin for your project's client ID."
error: "idpiframe_initialization_failed"

**Comment by bashbaugh** [comment]
Go to https://console.cloud.google.com/apis/credentials and select your OAuth client ID, then add http://localhost:3000 to your "Authorized redirect URIs" and "Authorized JavaScript origins"
